-- drop table delivery_order;
-- drop table outbox;
-- drop table delivery_order_report;

create table if not exists outbox (
    id           bigint GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL primary key ,
    aggregate_id bigint,
    type         text,
    payload      text,
    created_at   timestamp with time zone
);

create table if not exists delivery_order (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL primary key,
    address_id          int not null,
    user_id             int not null,
    product_ids         int array,
    provider_name       text,
    provider_order_id   int,
    created_at          timestamp with time zone,
    execute_at          timestamp with time zone
);

-- Сюда пишется информация в агрегированном виде, для быстрой выборки и отчетов
create table if not exists delivery_order_report (
    id                  bigint primary key ,
    address_id          int not null,
    address_payload     json,
    user_id             int not null,
    user_payload        json,
    product_ids         int array not null,
    created_at          timestamp with time zone,
    status              text,
    provider_name       text,
    provider_order_id   int,
    execute_at          timestamp with time zone
);

-- select * from final table (
--                   insert into delivery_order
-- (address_id, user_id, product_ids, provider_name, provider_order_id, created_at, execute_at, status)
-- values ( 1, 1, null, null, null, null, null, null)
--                   ) dr;